version: 2
jobs:
  build:
    working_directory: ~/pm-api.blueprint
    machine: true
    steps:
      - checkout
      - run:
          name: create dir
          command: mkdir blueprint.tmp
#      - run:
#          name: install aglio
#          command: npm install -g aglio
#      - run:
#          name: create blueprint
#          command: aglio -i spec/index.apib -o blueprint.tmp/index.html --theme-variables streak --theme-template triple
      - run:
          name: create blueprint
          command: docker run -ti --rm -v $PWD:/docs humangeo/aglio aglio -i /docs/spec/index.apib -o /docs/blueprint.tmp/index.html --theme-variables streak --theme-template triple
      - save_cache:
          key: blueprint-{{ epoch }}
          paths:
            - ~/pm-api.blueprint/blueprint.tmp

  deploy:
    working_directory: ~/pm-api.blueprint
    machine: true
    steps:
      - restore_cache:
          keys:
            - blueprint
      - run:
          name: deploy
          command: aws s3 sync ~/pm-api.blueprint/blueprint.tmp s3://nagashima-blueprint/

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: master

